#!/usr/bin/env python2.5

# coding=utf-8
# $HeadURL$
# $Id$

__version__ = "0.1"

__license__ = """
GHAFAS, a GTK+ client to query train connections & fares
Copyright 2007 tomfuks <casualcoding@gmail.com>

This file is part of GHAFAS.

GHAFAS is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

GHAFAS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with GHAFAS; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""


import sys
import os.path

apppath = sys.argv[0]


if os.path.exists(apppath + '.py'):
    path = os.path.dirname(apppath)
    app = os.path.basename(apppath) + '.py'
    if os.path.exists('/usr/bin/open-x11'):
        err = os.system('PATH=%s:$PATH /usr/bin/open-x11 %s' % (path, app))
    else:
        err = os.system(apppath + '.py')
    sys.exit(err)

if os.path.exists('/usr/bin/open'):
    os.system('open -a X11')


import ghafas

ghafas.Base().main()


