#!/usr/bin/env python

# coding=utf-8
# $HeadURL$
# $Id$

__version__ = "0.1"

__license__ = """
GHAFAS, a GTK+ client to query train connections & fares
Copyright 2007 tomfuks <casualcoding@gmail.com>

This file is part of GHAFAS.

GHAFAS is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

GHAFAS is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with GHAFAS; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""


try:
    # Try to run a installed release.
    import ghafas
    ghafas.main()

except ImportError:
    # Module ghafas not found; try to run it as a script.

    import sys
    import os.path

    # TODO: try to find python version which has pygtk installed.
    interpreter = 'python2.6'
    apppath = sys.argv[0]

    if os.path.exists(apppath + '.py'):
        cmd = '%s %s.py' % (interpreter, apppath)
        print cmd
        err = os.system(cmd)
        sys.exit(err)


