#!/usr/bin/env python2.5

# coding=utf-8
# $HeadURL: $
# $Id: $

__version__ = "0.1"

__license__ = """
GnaKB, a GTK+ client to query train connections & fares
Copyright 2007 tomfuks <xxxxxxxxxxxx>

This file is part of GnaKB.

Sonata is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

Sonata is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Sonata; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
"""


import sys
import os.path

path = os.path.dirname(sys.argv[0])
app = os.path.basename(sys.argv[0])

if os.path.exists('/usr/bin/open-x11'):
    os.system('PATH=%s:$PATH /usr/bin/open-x11 %s.py' % (path, app))
else:
    os.system('%s.py' % sys.argv[0])


